spring:
  application:
    name: api-gateway
  profiles:
    active: docker
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8080

app:
  jwt:
    secret: "mysecretkeymysecretkeymysecretkeymysecretkey"
    expiration-ms: 3600000

feign:
  circuitbreaker:
    enabled: true
