spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://postgres:5432/order_db
    password: password
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

feign:
  circuitbreaker:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,circuitbreakers,circuitbreakerevents,metrics,prometheus
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignoreExceptions:
          - com.amalitech.fooddelivery.orderservice.exception.ResourceNotFoundException
          - com.amalitech.fooddelivery.orderservice.exception.UnauthorizedException
    instances:
      restaurantService:
        baseConfig: default
      customerService:
        baseConfig: default
      deliveryService:
        baseConfig: default
        failureRateThreshold: 60
  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
    instances:
      restaurantService:
        baseConfig: default
      customerService:
        baseConfig: default
      deliveryService:
        baseConfig: default
        timeoutDuration: 5s
